### ISSUE TITLE
Childhood Mortality

### ISSUE THREAD

**Issue by stackpoint** [LaTueur/Deadly-Times#1]
Great work on your mod! Found it on [this post](https://www.reddit.com/r/CrusaderKings/comments/j86y5s/child_mortality_death_a_plea_for_higher_difficulty/) and something mentioned in the post that your mod doesn't(?) have is increased childhood morality:

> Having played CK3 for uh 323 hours now, I'm finding it too easy. It's especially too easy to plan for things to happen the way you want them to. And a lot of why that's the case is the lack of child mortality.
> 
> Some cursory reading suggests that in the middle ages, even if you were nobility, maybe a third of your children would not survive to adulthood. In CK3 nearly all of them do. 

It looks like there is a sickly trait for childhood that can be added on birth but it doesn't fire very often and may not be deadly enough.

**Comment by LaTueur** [comment]
Newborns getting the sickly trait and being stillborn is part of the pregnancy complications (because they are fired by the same event).
So the rule which increases them, also increases the chance of getting the sickly trait.
It already gives a huge debuf to health, increasing it would make it almost impossible to survive having it.
Just turn up pregnancy complication to extreme.

**Comment by stackpoint** [comment]
My thought is to increase the frequency of getting the trait in proportion of the other events because getting the sickly trait itself is not a death sentence to the child immediately and there are otherwise very few ways for the child to die after being born without the trait. Something like this:

![image](https://user-images.githubusercontent.com/5704491/95921989-06586a80-0d4e-11eb-911a-f04f1bdef88e.png)

Anyway, this isn't a big issue as I can mod it in myself, just wanted to make a possible suggestion.
